[workspace]
members = [
    "quarry-sdk",
    "oracle", "quarry-scripts", "bridge",
]

resolver = "2"

[profile.integration]
inherits = "dev"

[profile.dev]
panic = 'abort'

[profile.release]
panic = 'abort'
