[workspace]
members = [
    "quarry-sdk",
    "chain-tip-oracle", "quarry-scripts", "peg-in-oracle", "peg-out-oracle",
]

resolver = "2"

[profile.integration]
inherits = "dev"

[profile.dev]
panic = 'abort'

[profile.release]
panic = 'abort'
